# Generated by Django 5.2.17 on 2026-10-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Company Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=16, verbose_name='Role'),
        ),
    ]
