# Generated by Django 5.2.17 on 2026-09-30 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text area'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('multi_select', 'Multiple select'), ('checkbox', 'Checkbox')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.integration')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_integration_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='integrationfield',
            constraint=models.UniqueConstraint(fields=('integration', 'name'), name='unique_integration_field_name'),
        ),
    ]
