# Generated by Django 5.2.17 on 2026-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_required_email_phone_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationfield',
            name='system_key',
            field=models.CharField(choices=[('custom', 'Custom field'), ('email', 'Email'), ('phone', 'Phone number'), ('address_main', 'Main address'), ('address_street', 'Street'), ('address_city', 'City'), ('address_zipcode', 'ZIP code'), ('address_state', 'State')], default='custom', max_length=50),
        ),
    ]
